// Code generated by sqlc. DO NOT EDIT.
// source: admin.sql

package db

import (
	"context"
)

const checkAdmin = `-- name: CheckAdmin :one
SELECT id, username, password, role FROM admin WHERE role = "admin"
`

func (q *Queries) CheckAdmin(ctx context.Context) (Admin, error) {
	row := q.db.QueryRowContext(ctx, checkAdmin)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admin (
    username, password, role
)VALUES(
    ?,?,?
)
`

type CreateAdminParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.ExecContext(ctx, createAdmin, arg.Username, arg.Password, arg.Role)
	return err
}
