// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/golang/protobuf/ptypes/timestamp"
)

type Admin struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type Event struct {
	ID             int32               `json:"id"`
	JudulEvent     string              `json:"judul_event"`
	DeskripsiEvent string              `json:"deskripsi_event"`
	KriteriaEvent  string              `json:"kriteria_event"`
	TanggalEvent   timestamp.Timestamp `json:"tanggal_event"`
	IDAdmin        int                 `json:"id_admin"`
}

type Leaderboard struct {
	Ranking     int `json:"ranking"`
	IDMahasiswa int `json:"id_mahasiswa"`
	IDTantangan int `json:"id_tantangan"`
	IDSilabus   int `json:"id_silabus"`
}

type Mahasiswa struct {
	ID            int32               `json:"id"`
	UrlFoto       string              `json:"url_foto"`
	NamaLengkap   string              `json:"nama_lengkap"`
	TanggalLahir  timestamp.Timestamp `json:"tanggal_lahir"`
	JenisKelamin  string              `json:"jenis_kelamin"`
	AsalKampus    string              `json:"asal_kampus"`
	Nim           string              `json:"nim"`
	Jurusan       string              `json:"jurusan"`
	TahunMasuk    string              `json:"tahun_masuk"`
	KotaKabupaten string              `json:"kota_kabupaten"`
	IDTantangan   int                 `json:"id_tantangan"`
	IDSilabus     int                 `json:"id_silabus"`
	IDEvent       int                 `json:"id_event"`
	IDUser        int                 `json:"id_user"`
}

type Silabus struct {
	ID              int32  `json:"id"`
	JudulSilabus    string `json:"judul_silabus"`
	Definisi        string `json:"definisi"`
	FungsiSilabus   string `json:"fungsi_silabus"`
	Deskripsi       string `json:"deskripsi"`
	UrlVideoSilabus string `json:"url_video_silabus"`
	TaskSilabus     string `json:"task_silabus"`
	UjianSilabus    string `json:"ujian_silabus"`
	IDAdmin         int    `json:"id_admin"`
}

type StatusEvent struct {
	Checktantangan int `json:"checktantangan"`
	IDMahasiswa    int `json:"id_mahasiswa"`
	IDEvent        int `json:"id_event"`
}

type StatusSilabus struct {
	SkorSilabus  int `json:"skor_silabus"`
	IDMahasiswa  int `json:"id_mahasiswa"`
	IDSilabus    int `json:"id_silabus"`
	Checksilabus int `json:"checksilabus"`
}

type StatusTantangan struct {
	SkorTantangan  int `json:"skor_tantangan"`
	IDMahasiswa    int `json:"id_mahasiswa"`
	IDTantangan    int `json:"id_tantangan"`
	Checktantangan int `json:"checktantangan"`
}

type Tantangan struct {
	ID                int32  `json:"id"`
	JudulTantangan    string `json:"judul_tantangan"`
	Tema              string `json:"tema"`
	Latar             string `json:"latar"`
	UrlVideoTantangan string `json:"url_video_tantangan"`
	TaskTantangan     string `json:"task_tantangan"`
	UjianTantangan    string `json:"ujian_tantangan"`
	SkorTantangan     string `json:"skor_tantangan"`
	IDAdmin           int    `json:"id_admin"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Nomorhp  int    `json:"nomorhp"`
	Email    string `json:"email"`
}
