// Code generated by sqlc. DO NOT EDIT.
// source: silabus.sql

package db

import (
	"context"
)

const createSilabus = `-- name: CreateSilabus :exec
INSERT INTO silabus(
    id, judul_silabus, definisi, fungsi_silabus, deskripsi, url_video_silabus,task_silabus, ujian_silabus,id_admin
)VALUES(
    ?,?,?,?,?,?,?,?,?
)
`

type CreateSilabusParams struct {
	ID              int32  `json:"id"`
	JudulSilabus    string `json:"judul_silabus"`
	Definisi        string `json:"definisi"`
	FungsiSilabus   string `json:"fungsi_silabus"`
	Deskripsi       string `json:"deskripsi"`
	UrlVideoSilabus string `json:"url_video_silabus"`
	TaskSilabus     string `json:"task_silabus"`
	UjianSilabus    string `json:"ujian_silabus"`
	IDAdmin         int    `json:"id_admin"`
}

func (q *Queries) CreateSilabus(ctx context.Context, arg CreateSilabusParams) error {
	_, err := q.db.ExecContext(ctx, createSilabus,
		arg.ID,
		arg.JudulSilabus,
		arg.Definisi,
		arg.FungsiSilabus,
		arg.Deskripsi,
		arg.UrlVideoSilabus,
		arg.TaskSilabus,
		arg.UjianSilabus,
		arg.IDAdmin,
	)
	return err
}
