// Code generated by sqlc. DO NOT EDIT.
// source: leaderboard.sql

package db

import (
	"context"
)

const listLeaderboard = `-- name: ListLeaderboard :many
SELECT ranking, id_mahasiswa, id_tantangan, id_silabus FROM  leaderboard
`

func (q *Queries) ListLeaderboard(ctx context.Context) ([]Leaderboard, error) {
	rows, err := q.db.QueryContext(ctx, listLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaderboard
	for rows.Next() {
		var i Leaderboard
		if err := rows.Scan(
			&i.Ranking,
			&i.IDMahasiswa,
			&i.IDTantangan,
			&i.IDSilabus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
