// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Admin struct {
	ID       int32          `json:"id"`
	Username sql.NullString `json:"username"`
	Password sql.NullString `json:"password"`
	Role     sql.NullString `json:"role"`
}

type Event struct {
	ID             int32          `json:"id"`
	JudulEvent     sql.NullString `json:"judul_event"`
	DeskripsiEvent sql.NullString `json:"deskripsi_event"`
	KriteriaEvent  sql.NullString `json:"kriteria_event"`
	TanggalEvent   sql.NullString `json:"tanggal_event"`
	IDAdmin        sql.NullInt32  `json:"id_admin"`
}

type Leaderboard struct {
	Ranking     sql.NullInt32 `json:"ranking"`
	IDMahasiswa sql.NullInt32 `json:"id_mahasiswa"`
	IDTantangan sql.NullInt32 `json:"id_tantangan"`
	IDSilabus   sql.NullInt32 `json:"id_silabus"`
}

type Mahasiswa struct {
	ID            int32          `json:"id"`
	Username      sql.NullString `json:"username"`
	Password      sql.NullString `json:"password"`
	Nomorhp       sql.NullInt32  `json:"nomorhp"`
	Email         sql.NullInt32  `json:"email"`
	UrlFoto       sql.NullString `json:"url_foto"`
	NamaLengkap   sql.NullString `json:"nama_lengkap"`
	TanggalLahir  sql.NullString `json:"tanggal_lahir"`
	JenisKelamin  sql.NullString `json:"jenis_kelamin"`
	AsalKampus    sql.NullString `json:"asal_kampus"`
	Nim           sql.NullString `json:"nim"`
	Jurusan       sql.NullString `json:"jurusan"`
	TahunMasuk    sql.NullString `json:"tahun_masuk"`
	KotaKabupaten sql.NullString `json:"kota_kabupaten"`
	IDTantangan   sql.NullInt32  `json:"id_tantangan"`
	IDSilabus     sql.NullInt32  `json:"id_silabus"`
	IDEvent       sql.NullInt32  `json:"id_event"`
}

type Silabus struct {
	ID              int32          `json:"id"`
	JudulSilabus    sql.NullString `json:"judul_silabus"`
	Definisi        sql.NullString `json:"definisi"`
	FungsiSilabus   sql.NullString `json:"fungsi_silabus"`
	Deskripsi       sql.NullString `json:"deskripsi"`
	UrlVideoSilabus sql.NullString `json:"url_video_silabus"`
	TaskSilabus     sql.NullString `json:"task_silabus"`
	UjianSilabus    sql.NullString `json:"ujian_silabus"`
	SkorSilabus     sql.NullString `json:"skor_silabus"`
	IDAdmin         sql.NullInt32  `json:"id_admin"`
}

type Tantangan struct {
	ID                int32          `json:"id"`
	JudulTantangan    sql.NullString `json:"judul_tantangan"`
	Tema              sql.NullString `json:"tema"`
	Latar             sql.NullString `json:"latar"`
	UrlVideoTantangan sql.NullString `json:"url_video_tantangan"`
	TaskTantangan     sql.NullString `json:"task_tantangan"`
	UjianTantangan    sql.NullString `json:"ujian_tantangan"`
	SkorTantangan     sql.NullString `json:"skor_tantangan"`
	IDAdmin           sql.NullInt32  `json:"id_admin"`
}
